version: '3'

services:
  
  html:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "5500:5500"
    expose:
      - "5500"
    command: sleep infinity
